### ISSUE TITLE
运行报没有数据库的错误

### ISSUE THREAD

**Issue by yisake** [xuelangZF/NaHan#13]
数据库需要怎么初始化啊。。。

sqlalchemy.exc.OperationalError
OperationalError: (_mysql_exceptions.OperationalError) (1049, "Unknown database 'nahan'")

Traceback (most recent call last)
File "C:\NaHan\lib\site-packages\flask\app.py", line 2000, in __call__
return self.wsgi_app(environ, start_response)
File "C:\NaHan\lib\site-packages\flask\app.py", line 1991, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "C:\NaHan\lib\site-packages\flask\app.py", line 1567, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\NaHan\lib\site-packages\flask\app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "C:\NaHan\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\NaHan\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\NaHan\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "C:\NaHan\lib\site-packages\flask\app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "D:\Git\NaHan\nahan\voice\views.py", line 28, in index
topics = topics_all[offset:offset + per_page]
File "C:\NaHan\lib\site-packages\sqlalchemy\orm\query.py", line 2457, in __getitem__
return list(res)
File "C:\NaHan\lib\site-packages\sqlalchemy\orm\query.py", line 2761, in __iter__
return self._execute_and_instances(context)
File "C:\NaHan\lib\site-packages\sqlalchemy\orm\query.py", line 2774, in _execute_and_instances
close_with_result=True)
File "C:\NaHan\lib\site-packages\sqlalchemy\orm\query.py", line 2765, in _connection_from_session
**kw)
File "C:\NaHan\lib\site-packages\sqlalchemy\orm\session.py", line 893, in connection
execution_options=execution_options)
File "C:\NaHan\lib\site-packages\sqlalchemy\orm\session.py", line 898, in _connection_for_bind
engine, execution_options)
File "C:\NaHan\lib\site-packages\sqlalchemy\orm\session.py", line 334, in _connection_for_bind
conn = bind.contextual_connect()
File "C:\NaHan\lib\site-packages\sqlalchemy\engine\base.py", line 2039, in contextual_connect
self._wrap_pool_connect(self.pool.connect, None),
File "C:\NaHan\lib\site-packages\sqlalchemy\engine\base.py", line 2078, in _wrap_pool_connect
e, dialect, self)
File "C:\NaHan\lib\site-packages\sqlalchemy\engine\base.py", line 1405, in _handle_dbapi_exception_noconnection
exc_info
File "C:\NaHan\lib\site-packages\sqlalchemy\util\compat.py", line 202, in raise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "C:\NaHan\lib\site-packages\sqlalchemy\engine\base.py", line 2074, in _wrap_pool_connect
return fn()
File "C:\NaHan\lib\site-packages\sqlalchemy\pool.py", line 376, in connect
return _ConnectionFairy._checkout(self)
File "C:\NaHan\lib\site-packages\sqlalchemy\pool.py", line 713, in _checkout
fairy = _ConnectionRecord.checkout(pool)
File "C:\NaHan\lib\site-packages\sqlalchemy\pool.py", line 480, in checkout
rec = pool._do_get()
File "C:\NaHan\lib\site-packages\sqlalchemy\pool.py", line 1060, in _do_get
self._dec_overflow()
File "C:\NaHan\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
compat.reraise(exc_type, exc_value, exc_tb)
File "C:\NaHan\lib\site-packages\sqlalchemy\pool.py", line 1057, in _do_get
return self._create_connection()
File "C:\NaHan\lib\site-packages\sqlalchemy\pool.py", line 323, in _create_connection
return _ConnectionRecord(self)
File "C:\NaHan\lib\site-packages\sqlalchemy\pool.py", line 449, in __init__
self.connection = self.__connect()
File "C:\NaHan\lib\site-packages\sqlalchemy\pool.py", line 607, in __connect
connection = self.__pool._invoke_creator(self)
File "C:\NaHan\lib\site-packages\sqlalchemy\engine\strategies.py", line 97, in connect
return dialect.connect(*cargs, **cparams)
File "C:\NaHan\lib\site-packages\sqlalchemy\engine\default.py", line 385, in connect
return self.dbapi.connect(*cargs, **cparams)
File "C:\NaHan\lib\site-packages\MySQLdb\__init__.py", line 81, in Connect
return Connection(*args, **kwargs)
File "C:\NaHan\lib\site-packages\MySQLdb\connections.py", line 193, in __init__
super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (_mysql_exceptions.OperationalError) (1049, "Unknown database 'nahan'")
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by selfboot** [comment]
[Mysql 服务](https://github.com/xuelangZF/ehpc/wiki/%E9%A1%B9%E7%9B%AE%E9%83%A8%E7%BD%B2#mysql-%E6%9C%8D%E5%8A%A1)

[Flask-Migrate](https://github.com/xuelangZF/ehpc/wiki/Flask-%E6%89%A9%E5%B1%95%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8#flask-migrate) 

网上可以搜 flask mysql 部署。后面系列博客会告诉如何部署。

**Comment by yisake** [comment]
我是自己创建了nahan的库，然后upgrade就ok了，
还有请问下，部署的机器http://bbs.selfboot.cn/是免费的吗？怎么申请和搭建？

**Comment by selfboot** [comment]
我是买的 Digital Ocean 的 VPS，然后放在上面的，官网有详细的教程教你搭建。

不过推荐买 vultr 家的，有东京节点，速度很快，还可以架设一个 ss 用来上网。注册的话，可以用我的邀请链接：http://www.vultr.com/?ref=7017686

**Comment by yisake** [comment]
看不懂啊，收费怎么样啊

**Comment by selfboot** [comment]
一个月 5$ 的配置就可以了。

**Comment by yisake** [comment]
等我扩展点自己的东西再看看这个，请教一个问题，请求这个http://127.0.0.1:5000/nodes是有什么用啊？
节点是用来？小弟刚学flask不久。。。

**Comment by selfboot** [comment]
相当于把话题分类吧，好多论坛（比如 V2EX）都有这个，我也模仿了一下。

**Comment by yisake** [comment]
大神赞啊，以后跟着你混了。。

**Comment by yisake** [comment]
大神目前在哪家公司啊？

**Comment by selfboot** [comment]
我还没毕业。。。不是大神。。。
