### ISSUE TITLE
Problems in install python package.

### ISSUE THREAD

**Issue by selfboot** [xuelangZF/NaHan#9]
On Ubuntu:

`$ pip install Pillow`

may fails with this error:

> ValueError: --enable-jpeg requested but jpeg not found, aborting.

When install MySQL-python, may fails too:

> rmicro@ubuntu:~$ pip install MySQL-python
> Downloading/unpacking MySQL-python
>   Downloading MySQL-python-1.2.3.tar.gz (70Kb): 70Kb downloaded
>   Running setup.py egg_info for package MySQL-python
>     sh: mysql_config: not found
>     Traceback (most recent call last):
>       File "<string>", line 14, in <module>
>       File "/home/rmicro/build/MySQL-python/setup.py", line 15, in <module>
>         metadata, options = get_config()
>       File "setup_posix.py", line 43, in get_config
>         libs = mysql_config("libs_r")
>       File "setup_posix.py", line 24, in mysql_config
>         raise EnvironmentError("%s not found" % (mysql_config.path,))
>     EnvironmentError: mysql_config not found
>     Complete output from command python setup.py egg_info:
>     sh: mysql_config: not found
> ---
> 
> Command python setup.py egg_info failed with error code 1

**Comment by selfboot** [comment]
This can help:

[Installing MySQL-python](http://stackoverflow.com/questions/7459766/installing-mysql-python)
[Error installing Pillow on ubuntu 14.04](http://stackoverflow.com/questions/32942861/error-installing-pillow-on-ubuntu-14-04)
